import { useCallback, useEffect, useRef, useState, type ReactNode } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { api, type StudyPlan } from '../api/client';
import { BoardHost } from '../board/BoardHost';
import { BoardPrompt } from '../board/BoardPrompt';
import { FirstMeeting } from '../board/FirstMeeting';
import type { MeetingAnswers } from '../board/meeting';
import { InputBar } from '../board/InputBar';
import { decideAsk } from '../board/detour';
import type { Beat, BoardScript } from '../board/types';
import { classifyFailure, isOffline } from '../net/offline';
import { pickAndEncodeImage, type EncodedImage } from '../net/image';
import { planGenFailure, type GenMessageKey } from '../board/genRetry';
import { strings, type Lang } from '../i18n';

type Phase = 'greeting' | 'meeting' | 'lesson' | 'transition' | 'complete';
type ProgressPatch = {
  status?: 'started' | 'passed';
  quiz_score?: number | null;
  last_completed_beat?: number | null;
  mastered?: boolean;
};

/**
 * The path on the board (§8.12), now with the single input (§8.5). One
 * continue-prompt greets on arrival and, after a pass, asks whether to go straight
 * into the next topic. The bottom input lets the student, mid-lesson: type a
 * different topic or attach a photo — a **detour** that plays now and returns to
 * the plan topic (resumed) afterward — or ask a follow-up, which appends a
 * re-explanation to the current board. Progress, resume, and generation key on the
 * **active** topic (a detour or the plan topic); the plan only advances on a pass
 * of the plan topic itself.
 */
export function PathBoardScreen({
  session,
  name,
  language,
  initialPlan,
  onExit,
}: {
  session: string;
  name: string | null;
  language: Lang;
  initialPlan: StudyPlan;
  onExit: () => void;
}) {
  const t = strings[language];
  const [plan, setPlan] = useState<StudyPlan>(initialPlan);
  const [phase, setPhase] = useState<Phase>(initialPlan.current_topic_id ? 'greeting' : 'complete');
  const [greeting, setGreeting] = useState<string | undefined>(undefined);
  const [script, setScript] = useState<BoardScript | null>(null);
  const [resumeFromBeatId, setResumeFromBeatId] = useState<number | null>(null);
  const [failure, setFailure] = useState<{ messageKey: GenMessageKey; showManualRetry: boolean } | null>(null);
  // A detour to an out-of-path topic requested via the input (§8.12). Its script
  // comes straight from the ask response, so it isn't (re)generated by the effect.
  const [detour, setDetour] = useState<{ topicId: string } | null>(null);
  // A re-explanation segment to append to the live board (§8.5).
  const [reexplain, setReexplain] = useState<{ nonce: number; beats: Beat[] } | null>(null);
  const [inputBusy, setInputBusy] = useState(false);
  const [inputNotice, setInputNotice] = useState<string | null>(null);
  // 'reply' is Bixy talking (Part 05 §8); 'warn' is the board reporting a problem.
  const [noticeTone, setNoticeTone] = useState<'warn' | 'reply'>('warn');
  // Bumping this re-runs the generation effect (an automatic or manual reload).
  const [reloadKey, setReloadKey] = useState(0);
  const [retestRound, setRetestRound] = useState(0);
  const autoReloadsRef = useRef(0);
  const advancedFor = useRef<Set<string>>(new Set());

  const activeTopicId = detour?.topicId ?? plan.current_topic_id;

  useEffect(() => {
    autoReloadsRef.current = 0;
  }, [activeTopicId]);

  // What happens on arrival (§8.12, Part 05 §7): a brand-new student meets Bixy
  // first; after that the greeting varies by recency — full the first visit of a
  // day, a short "welcome back" after. Fetched once on arrival.
  useEffect(() => {
    if (phase !== 'greeting' || !plan.current_topic_id) return;
    let active = true;
    (async () => {
      try {
        const variant = await api.postGreeting(session);
        if (!active) return;
        if (variant === 'first_meeting') {
          setPhase('meeting');
          return;
        }
        setGreeting(variant === 'short' ? t.welcomeBack(name ?? '') : t.greeting(name ?? ''));
      } catch {
        // A failed lookup falls back to the plain greeting, never to the meeting:
        // re-introducing Bixy to someone it has already met is the worse miss.
        if (active) setGreeting(t.greeting(name ?? ''));
      }
    })();
    return () => {
      active = false;
    };
    // Only re-run when we return to the greeting for a brand-new arrival.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [phase === 'greeting']);

  // Part 05 §7: finishing OR skipping ends the meeting for good. The answers go
  // up best-effort and the student moves straight on — the first lesson is what
  // they came for, and it never waits on this.
  const finishMeeting = useCallback(
    (answers: MeetingAnswers) => {
      api.postProfile(session, answers);
      setGreeting(t.greeting(name ?? ''));
      setPhase('greeting');
    },
    [session, name, t],
  );

  const fetchResume = useCallback(
    async (topicId: string): Promise<{ beat: number | null; retestRound: number }> => {
      try {
        const record = (await api.getProgress(session)).find((p) => p.topic_id === topicId);
        return {
          beat: record && record.status !== 'passed' ? record.last_completed_beat : null,
          // Carries §6's second-miss escalation across a session boundary.
          retestRound: record?.retest_round ?? 0,
        };
      } catch {
        return { beat: null, retestRound: 0 }; // best-effort; fall back to the top.
      }
    },
    [session],
  );

  // Generate the plan topic's lesson (§8.12), resuming from the saved beat (§9.1).
  // A detour's script is set imperatively from the ask response, so this skips it.
  useEffect(() => {
    if (phase !== 'lesson' || detour) return;
    const topicId = plan.current_topic_id;
    if (!topicId) {
      setPhase('complete');
      return;
    }
    let active = true;
    setScript(null);
    setFailure(null);
    (async () => {
      try {
        const [{ board_script }, resumeBeat] = await Promise.all([
          api.generateLesson(session, { topic_id: topicId, language }),
          fetchResume(topicId),
        ]);
        if (!active) return;
        setResumeFromBeatId(resumeBeat.beat);
        setRetestRound(resumeBeat.retestRound);
        setScript(board_script);
      } catch (e) {
        if (!active) return;
        // §8.10: a stuck model auto-reloads (capped); a real failure or an offline
        // student stops with a plain message instead of a silent loop.
        const decision = planGenFailure(classifyFailure(e, !isOffline()), autoReloadsRef.current);
        if (decision.autoReload) {
          autoReloadsRef.current += 1;
          setReloadKey((k) => k + 1);
        } else {
          setFailure({ messageKey: decision.messageKey, showManualRetry: decision.showManualRetry });
        }
      }
    })();
    return () => {
      active = false;
    };
  }, [phase, plan.current_topic_id, detour, session, language, reloadKey, fetchResume]);

  // Manual retry (§8.10): a deliberate re-attempt gets a fresh auto-reload budget.
  const retryLesson = useCallback(() => {
    autoReloadsRef.current = 0;
    setFailure(null);
    setScript(null);
    setReloadKey((k) => k + 1);
  }, []);

  // Persist progress; on a pass of the *plan* topic (not a detour), advance the
  // path (§8.12). A detour pass is recorded — the server skips it when the plan
  // later reaches it — but never advances the plan from under the student.
  const handleProgress = useCallback(
    (patch: ProgressPatch) => {
      const topicId = activeTopicId;
      if (!topicId) return;
      api.putProgress(session, topicId, patch);
      if (patch.status === 'passed' && !detour && !advancedFor.current.has(topicId)) {
        advancedFor.current.add(topicId);
        (async () => {
          const updated = await api.advanceStudyPlan(session, topicId).catch(() => null);
          if (updated) {
            setPlan(updated);
            setPhase(updated.current_topic_id ? 'transition' : 'complete');
          }
        })();
      }
    },
    [session, activeTopicId, detour],
  );

  // Part 04 §6: the shorter retest after a re-teach. Server-selected from the
  // student's persisted misses plus the topic's variant pool; an empty result
  // means nothing is stored yet, and the board falls back to the full test.
  const requestRetest = useCallback(async () => {
    if (!activeTopicId) return [];
    try {
      const { quiz } = await api.retest(session, { topic_id: activeTopicId, language });
      return quiz;
    } catch {
      return [];
    }
  }, [session, activeTopicId, language]);

  // Part 04 §13: the check-in that closes out a detour. Each call rotates past
  // the last question served, so a wrong answer re-asks and gets a different one.
  const requestWrapUp = useCallback(async () => {
    if (!detour) return null;
    try {
      const { question } = await api.wrapUp(session, { topic_id: detour.topicId, language });
      return question;
    } catch {
      return null; // no check-in is better than a stuck detour.
    }
  }, [session, detour, language]);

  // Leave a detour and return to the plan topic, resumed where the student left it.
  const returnToPlan = useCallback(() => {
    setDetour(null);
    setReexplain(null);
    setScript(null);
    setInputNotice(null);
    autoReloadsRef.current = 0;
    setReloadKey((k) => k + 1);
  }, []);

  // A submitted input (§8.5): a new topic (detour), a follow-up (re-explanation),
  // or off-topic. The board itself stays put until we clearly start a new topic.
  const handleAsk = useCallback(
    async (input: { text?: string; image?: EncodedImage }) => {
      setInputBusy(true);
      setInputNotice(null);
      setNoticeTone('warn');
      try {
        const result = await api.ask(session, {
          text: input.text,
          image: input.image,
          language,
          current_topic_id: activeTopicId,
        });
        const decision = decideAsk(result, activeTopicId);
        if (decision.action === 'detour') {
          autoReloadsRef.current = 0;
          setReexplain(null);
          setResumeFromBeatId(null); // a fresh detour starts from the top
          setRetestRound(0);
          setFailure(null);
          setScript(decision.boardScript);
          setDetour({ topicId: decision.topicId });
        } else if (decision.action === 'replay') {
          setReexplain(null);
          setResumeFromBeatId(null);
          setScript(decision.boardScript);
        } else if (decision.action === 'reexplain') {
          setReexplain((prev) => ({ nonce: (prev?.nonce ?? 0) + 1, beats: decision.beats }));
        } else if (decision.action === 'identity') {
          // Bixy answering what it is (Part 05 §8) — spoken back to the student,
          // leaving the board exactly as it was. It's a reply, not a lesson.
          setInputNotice(decision.text);
          setNoticeTone('reply');
        } else {
          setInputNotice(t.askOffTopic);
        }
      } catch (e) {
        setInputNotice(isOffline() ? t.offline : t.lessonFailed);
      } finally {
        setInputBusy(false);
      }
    },
    [session, language, activeTopicId, t],
  );

  const handleAttach = useCallback(async () => {
    setInputNotice(null);
    const picked = await pickAndEncodeImage();
    if (picked === null) return; // cancelled
    if (typeof picked === 'string') {
      setInputNotice(
        picked === 'too_large' ? t.imageTooLarge : picked === 'unsupported' ? t.imageUnsupported : t.imageUnreadable,
      );
      return;
    }
    await handleAsk({ image: picked });
  }, [handleAsk, t]);

  if (phase === 'complete') {
    return (
      <Centered>
        <Text style={styles.complete}>{t.pathComplete}</Text>
        <Pressable style={styles.cta} onPress={onExit} accessibilityRole="button">
          <Text style={styles.ctaText}>{t.toYourPlan}</Text>
        </Pressable>
      </Centered>
    );
  }

  if (phase === 'meeting') {
    return <FirstMeeting t={t} onDone={finishMeeting} />;
  }

  if (phase === 'greeting' || phase === 'transition') {
    const isTransition = phase === 'transition';
    return (
      <BoardPrompt
        greeting={isTransition ? undefined : greeting}
        question={isTransition ? t.passedContinue : t.continueQuestion}
        yesLabel={t.continueYes}
        noLabel={t.continueNo}
        onYes={() => setPhase('lesson')}
        onNo={onExit}
      />
    );
  }

  // phase === 'lesson'
  if (failure) {
    // 'lessonTimeoutRetrying' is only produced while auto-reloading (which shows
    // the spinner, not this block), so it maps to the neutral preparing text.
    const messages: Record<GenMessageKey, string> = {
      offline: t.offline,
      lessonTimeoutRetrying: t.generatingLesson,
      lessonTimeoutFailed: t.lessonTimeoutFailed,
      lessonFailed: t.lessonFailed,
      noContent: t.noContent,
    };
    return (
      <Centered>
        <Text style={styles.error}>{messages[failure.messageKey]}</Text>
        {failure.showManualRetry ? (
          <Pressable style={styles.cta} onPress={retryLesson} accessibilityRole="button">
            <Text style={styles.ctaText}>{t.tryAgain}</Text>
          </Pressable>
        ) : null}
        <Pressable style={styles.linkButton} onPress={onExit} accessibilityRole="button">
          <Text style={styles.backText}>{t.toYourPlan}</Text>
        </Pressable>
      </Centered>
    );
  }
  if (!script) {
    return (
      <Centered>
        <Text style={styles.info}>{t.generatingLesson}</Text>
        <ActivityIndicator color="#5aa9ff" />
      </Centered>
    );
  }
  return (
    <View style={styles.fill}>
      <Pressable
        onPress={detour ? returnToPlan : onExit}
        style={styles.back}
        accessibilityRole="button"
      >
        <Text style={styles.backText}>{detour ? t.detourReturn : t.toYourPlan}</Text>
      </Pressable>
      <BoardHost
        initialRetestRound={retestRound}
        onRequestRetest={requestRetest}
        detour={
          detour
            ? {
                requestWrapUp,
                // Auto-return (Part 04 §13). The manual control above stays as a
                // fallback, but the normal path no longer depends on the student
                // noticing it — not noticing it is what made interrupted topics
                // look abandoned in the first place.
                onComplete: returnToPlan,
              }
            : undefined
        }
        // Remount on a topic switch (detour ↔ plan) so playback + resume restart cleanly.
        key={activeTopicId ?? 'none'}
        script={script}
        resumeFromBeatId={resumeFromBeatId}
        appendSegment={reexplain ? { nonce: reexplain.nonce, note: t.reexplainNote, beats: reexplain.beats } : undefined}
        gradeFillIn={async (q, answer) => {
          const { correct } = await api.gradeFillIn(session, {
            question: q.question,
            accepted_answers: q.accepted_answers ?? [],
            answer,
          });
          return correct;
        }}
        onProgress={handleProgress}
      />
      {inputNotice ? (
        <Text style={[styles.notice, noticeTone === 'reply' && styles.noticeReply]}>{inputNotice}</Text>
      ) : null}
      <InputBar
        placeholder={t.inputPlaceholder}
        attachLabel={t.attachPhoto}
        busy={inputBusy}
        onSend={(text) => handleAsk({ text })}
        onAttach={handleAttach}
      />
    </View>
  );
}

function Centered({ children }: { children: ReactNode }) {
  return <View style={styles.center}>{children}</View>;
}

const styles = StyleSheet.create({
  fill: { flex: 1, backgroundColor: '#12151c' },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#12151c', gap: 16, padding: 28 },
  info: { color: '#98a2b3', fontSize: 15 },
  error: { color: '#ff6b6b', fontSize: 16, textAlign: 'center' },
  notice: { color: '#f0b429', fontSize: 14, textAlign: 'center', paddingHorizontal: 16, paddingBottom: 4 },
  noticeReply: { color: '#e6e8ee', fontSize: 16, lineHeight: 22 },
  complete: { color: '#e6e8ee', fontSize: 24, textAlign: 'center', lineHeight: 32 },
  back: { position: 'absolute', top: 14, right: 18, zIndex: 1 },
  linkButton: { paddingVertical: 6 },
  backText: { color: '#5b6472', fontSize: 13, textDecorationLine: 'underline' },
  cta: { backgroundColor: '#5aa9ff', borderRadius: 12, paddingVertical: 12, paddingHorizontal: 24 },
  ctaText: { color: '#0b0e14', fontSize: 18, fontWeight: '600' },
});
